name: lint test build
on: push
jobs:
    lint:
        runs-on: window-latest
        steps:
            - name: Get the code
              uses: actions/checkout@v3
            - name: Install Nodejs
              uses: actions/setup-node@v3
              with:
                node-version 18
            - name: Install dependencies
              run: npm ci
            - name: Lint
              runs: npm lint
    
    test:
        needs: lint
        runs-on: window-latest
        
            steps:
            - name: Get the code
              uses: actions/checkout@v3
            - name: Install Nodejs
              uses: actions/setup-node@v3
              with:
                node-version 18
            - name: Install dependencies
              run: npm ci
            - name: Lint
              runs: npm test