name: lint test build
on: workflow_dispatch
jobs:
    lint:
        runs-on: windows-latest
        steps:
            - name: Get the code
              uses: actions/checkout@v3

            - name: Install Nodejs
              uses: actions/setup-node@v3
              with:
                node-version: 18

            - name: Install dependencies
              run: npm ci
            - name: Lint
              run: npm  run lint
    
    test:
        # needs: lint
        runs-on: windows-latest
        steps:
            - name: Get the code
              uses: actions/checkout@v3

            - name: Install Nodejs
              uses: actions/setup-node@v3
              with:
                node-version: 18

            - name: Install dependencies
              run: npm ci

            - name: Lint
              run: npm run test
    build:
        # needs: test
        runs-on: windows-latest
        steps: 
            - name: Get the code
              uses: actions/checkout@v3
            - name: Install nodejs
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: install dependencies
              run: npm ci

            - name: build
              run : npm run build